### ISSUE TITLE
Data People Starter Pack

### ISSUE THREAD

**Issue by menzenski** [ericclemmons/awesome-starter-packs#1]
### Link to Starter Pack

https://bsky.app/starter-pack/christiannolan.bsky.social/3l7cddlz5ja24

### Starter Pack Owner's Handle

@christiannolan.bsky.social

### Link to announcement post

https://bsky.app/profile/christiannolan.bsky.social/post/3l7cexotwa22o

### Recommended section

Role > Data

**Comment by ericclemmons** [comment]
Added via d984131d475123b99ec9f8c5ba3c658e9bf4b495
