### ISSUE TITLE
Tech Managers Starter Pack

### ISSUE THREAD

**Issue by menzenski** [ericclemmons/awesome-starter-packs#12]
### Link to Starter Pack

https://bsky.app/starter-pack/pelayoarbues.com/3l7iprxa5bf23

### Starter Pack Owner's Name

@pelayoarbues.com

### Link to announcement post

https://bsky.app/profile/pelayoarbues.com/post/3l7nx4mbjta2s

### Recommended section

Roles > Engineering Managers

**Comment by ericclemmons** [comment]
d984131d475123b99ec9f8c5ba3c658e9bf4b495
