### ISSUE TITLE
Platform Engineering Starter Pack

### ISSUE THREAD

**Issue by menzenski** [ericclemmons/awesome-starter-packs#2]
### Link to Starter Pack

https://bsky.app/starter-pack/did:plc:fzj6dm5dg6avzc6vgvxh4fgf/3l7pz6aoenx2s

### Starter Pack Owner's Handle

@bryanross.me

### Link to announcement post

https://bsky.app/profile/bryanross.me/post/3l7qdk2dzck2e

### Recommended section

Technology > Platform Engineering

**Comment by ericclemmons** [comment]
Resolved via d984131d475123b99ec9f8c5ba3c658e9bf4b495
