### ISSUE TITLE
Linguistics Starter Pack

### ISSUE THREAD

**Issue by menzenski** [ericclemmons/awesome-starter-packs#3]
### Link to Starter Pack

https://bsky.app/starter-pack/gretchenmcc.bsky.social/3l2jvzdh2bi2n

### Starter Pack Owner's Handle

@gretchenmcc.bsky.social

### Link to announcement post

https://bsky.app/profile/gretchenmcc.bsky.social/post/3l6q3pk6esf23

### Recommended section

Topic > Linguistics

**Comment by ericclemmons** [comment]
Closed via 91404072ed14fb8cfc476955890f94196d8e9d5c
