### ISSUE TITLE
Infrastructure Engineers Starter Pack

### ISSUE THREAD

**Issue by menzenski** [ericclemmons/awesome-starter-packs#4]
### Link to Starter Pack

https://bsky.app/starter-pack/chris.blue/3l7cfdtapwz2l

### Starter Pack Owner's Handle

@chris.blue

### Link to announcement post

https://bsky.app/profile/chris.blue/post/3l7cfiy5jrc2s

### Recommended section

Role > Infrastructure

**Comment by ericclemmons** [comment]
Closed via 91404072ed14fb8cfc476955890f94196d8e9d5c
