### ISSUE TITLE
AWS Serverless People Starter Pack

### ISSUE THREAD

**Issue by menzenski** [ericclemmons/awesome-starter-packs#6]
### Link to Starter Pack

https://bsky.app/starter-pack/tobilg.com/3l7gkycyvc52t

### Starter Pack Owner's Handle

@tobilg.com

### Link to announcement post

https://bsky.app/profile/tobilg.com/post/3l7i7xtd7l72y

### Recommended section

Role > AWS Serverless

**Comment by ericclemmons** [comment]
Closed via 91404072ed14fb8cfc476955890f94196d8e9d5c
